version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/gradle
  gradle: circleci/gradle@3.0.0

workflows:
  verify:
    jobs:
      - gradle/test:
        # https://circleci.com/developer/ja/images/image/cimg/openjdk
        - image: cimg/openjdk:17.0
